---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traffic-permissions-per-svc
  namespace: kubernetes-resource-creator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traffic-permissions-per-svc
rules:
- apiGroups: ["krc.io"]
  resources: ["operators"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["yourservicemesh.api"]
  resources: ["traffic-permissions"]
  verbs: ["get", "watch", "list", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traffic-permissions-per-svc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traffic-permissions-per-svc
subjects:
  - kind: ServiceAccount
    name: traffic-permissions-per-svc
    namespace: kubernetes-resource-creator
