apiVersion: "krc.io/v1"
kind: Operator
metadata:
  name: namespace-watcher
spec:
  config: |
    configVersion: v1
    kubernetes:
    - name: OnCreateNamespace
      apiVersion: v1
      kind: Namespace
      executeHookOnEvent:
      - Added
      fieldSelector:
        matchExpressions:
        - field: "metadata.name"
          operator: "NotEquals"
          value: "default"
        - field: "metadata.name"
          operator: "NotEquals"
          value: "kube-system"
        - field: "metadata.name"
          operator: "NotEquals"
          value: "kube-public"
        - field: "metadata.name"
          operator: "NotEquals"
          value: "kube-node-lease"
        - field: "metadata.name"
          operator: "NotEquals"
          value: "kubernetes-resources-creator"
  resources:
    default_service_account: |
      ---
      operation: CreateOrUpdate
      object:
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: default-rbac-permissions-sa
          namespace: {{ object.metadata.name }}
    default_netpol: |
      ---
      operation: CreateOrUpdate
      object:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: default-deny-ingress
          namespace: {{ object.metadata.name }}
        spec:
          podSelector: {}
          policyTypes:
          - Ingress
