apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: operators.krc.io
spec:
  group: krc.io
  scope: Cluster
  names:
    kind: Operator
    singular: operator
    plural: operators
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                config:
                  type: string
                resources:
                  type: object
                  additionalProperties:
                    type: string
