---
apiVersion: v1
kind: Pod
metadata:
  name: namespace-watcher
  namespace: kubernetes-resource-creator
spec:
  containers:
  - name: namespace-watcher
    image: 192.168.122.178:5000/krc:test
    imagePullPolicy: Always
    command:
      - /bin/sh
    args:
      - "-c"
      - "while true; do sleep 3600; done"
  serviceAccountName: namespace-watcher
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
