---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-watcher
  namespace: kubernetes-resource-creator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-watcher
rules:
- apiGroups: ["krc.io"]
  resources: ["operators"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "watch", "list", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-watcher
subjects:
  - kind: ServiceAccount
    name: namespace-watcher
    namespace: kubernetes-resource-creator
